#!/bin/bash
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

shopt -s extglob

declare maxprocs='16'

IFS=$'\n'

ucurl() {
    curl -L -g -s --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' -H 'elektrodaLang=pl' --compressed "$@"
}

declare -r arg0="$(basename "$0")"

usage() {
    printf '%s [dir]\nAdd pages to dir\n' "$arg0"
}

usage() {
    printf '%s [OPTION]... [DIR] [URL]...\n' "${0##*/}"
    printf 'Download, convert to json and save pages from URL in DIR.\n\n'
    printf 'Options:\n  -p,\t--max-procs NUM\tset number of processes to run at a time, by default set to 16\n'
    printf '  -h,\t--help\t\tshow this message\n\n'
    printf 'Note that options ought to be specified before the directory.\n'
}

get_json() {
    local -r rh="${1%.html}"
    local -r name="${rh#https://*/rtvforum/topic}"
    [ -e "$name" ] && return
    echo "$1"
    local -r t="$(ucurl "$1")"
    {
    echo "$1" #link
    echo "$(hgrep 'h1 +id="topic-title-editor" | "%i\n"' <<< "$t" | sed '/^$/d')" #title
    echo "$(hgrep 'span +itemprop="name" | "%i\n"' <<< "$t" | awk '!seen[$0]++' | sed '1,2d; :x; $!{N;s/\n/\//;bx}')" #path
    echo "$(hgrep 'span +class="time" | "%i\n"' <<< "$t" | sed 's/^.*> //; s/ *$//')" #time
    echo "$(hgrep 'span +class="views" | "%i\n"' <<< "$t" | sed 's/^.*> //; s/ //g')" #views
    echo "$(hgrep 'span +class="replies" | "%i\n"' <<< "$t" | sed 's/^.*> //; s/ //g')" #replies
    if hgrep 'a +class="reply-bttn" | "%i\n"' <<< "$t" | grep -q 'Zamkni'
    then
        echo 'true'
    else
        echo 'false'
    fi

    paste <(hgrep 'span +class="hidden-xs" | "%i\n"' <<< "$t") <(hgrep 'div +class="level" | "%i\n"' <<< "$t" | grep -o '[0-9]*') <(hgrep 'div +class="sec-a "; time +datetime | "%(datetime)a\n"' <<< "$t") <(hgrep 'div +id="post-content-[0-9]*"; div +class="text-wrap"' <<< "$t" | tr '\t\r\n' '   ' | hgrep -F 'div +class="text-wrap" | "%i\n"')
    } | recode ISO-8859-2..UTF8 | jq -RnMcs '
        (inputs | split("\n")) as $lines | 

        .["link"]=$lines[0] |
        .["title"]=$lines[1] |
        .["path"]=$lines[2] |
        .["time"]=$lines[3] |
        .["views"]=$lines[4] |
        .["replies"]=$lines[5] |
        .["locked"]=$lines[6] |
        .["posts"]=($lines[7:-1] | map(split("\t") | { ("author"):.[0] , ("level"):.[1] , ("time"):.[2] , ("text"):.[3] }))' > "$name"
}

get_sitemap() {
    for j in $(ucurl "$1" | hgrep 'loc @m"^https://www.elektroda.pl/rtvforum/topic[0-9]*" | "%i\n"')
    do
       [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
        get_json "$j" &
    done
}

get_sitemaps() {
	for i in $(ucurl 'https://www.elektroda.pl/sitemap.xml' | hgrep 'loc @m"^https://www.elektroda.pl/forum-gf[0-9]*" | "%i\n"')
	do
        echo "$i"
        get_sitemap "$i"
	done
}

get_page() {
    for j in $(ucurl "$1" | hgrep 'tr; h2; a | "https://www.elektroda.pl%(href)a\n"')
    do
       [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
       get_json "$j" &
    done
}

get_forum() {
    next="$1"
    while :
    do
        echo "$next"
        t1="$(ucurl "$next")"
        next="$(hgrep 'a +class="next" | "https://www.elektroda.pl%(href)a\n"' <<< "$t1" | head -n1)"
        for j in $(hgrep 'tr; h2; a | "https://www.elektroda.pl%(href)a\n"' <<< "$t1")
        do
            [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
            get_json "$j" &
        done
        [ -z "$next" ] && break
    done
}

get_forums() {
    for i in $(ucurl 'https://www.elektroda.pl/rtvforum/forums.html' | hgrep 'div +id="category-[0-9]*"; a +href="/rtvforum/forum[0-9]*\.html" | "https://www.elektroda.pl%(href)a\n"')
	do
        get_forum "$i"
	done
}

while [ "$#" -gt 0 ]
do
    case "$1" in
        -p|--max-procs) maxprocs="$2"; shift;;
        -h|--help) usage >&2; exit;;
        -*) usage >&2; exit 1;;
        *) break;;
    esac
    shift
done

if [ "$#" -lt '1' ]
then
    usage >&2
    exit 1
fi

cd "$1" || exit 1

while [ "$#" -gt 0 ]
do
    case "$1" in
        https://www.elektroda.pl?([/])|elektroda|https://www.elektroda.pl/sitemap.xml|sitemap)
            get_sitemaps;;

        https://www.elektroda.pl/forum-gf+([[:digit:]])-+([[:digit:]]).xml|https://www.elektroda.pl/forum-gf+([[:digit:]]).xml)
            get_sitemap "$1";;
        forum-gf+([[:digit:]])-+([[:digit:]]).xml|forum-gf+([[:digit:]]).xml)
            get_sitemap "https://www.elektroda.pl/$1";;
        forum-gf+([[:digit:]])|forum-gf+([[:digit:]])-+([[:digit:]]))
            get_sitemap "https://www.elektroda.pl/$1.xml";;

        forums)
            get_forums;;
        https://www.elektroda.pl/rtvforum/forum+([[:digit:]]).html)
            get_forum "$1";;
        forum+([[:digit:]]).html)
            get_forum "https://www.elektroda.pl/rtvforum/$1";;
        forum+([[:digit:]]))
            get_forum "https://www.elektroda.pl/rtvforum/$1.html";;

        https://www.elektroda.pl/rtvforum/forum+([[:digit:]])-+([[:digit:]]).html)
            get_page "$1";;
        forum+([[:digit:]])-+([[:digit:]]).html)
            get_page "https://www.elektroda.pl/rtvforum/$1";;
        forum+([[:digit:]])-+([[:digit:]]))
            get_page "https://www.elektroda.pl/rtvforum/$1.html";;

        https://www.elektroda.pl/rtvforum/topic+([[:digit:]]).html)
            get_json "$1";;
        +([[:digit:]]).html)
            get_json "https://www.elektroda.pl/rtvforum/topic$1";;
        +([[:digit:]]))
            get_json "https://www.elektroda.pl/rtvforum/topic$1.html";;
        topic+([[:digit:]]).html)
            get_json "https://www.elektroda.pl/rtvforum/$1";;
        topic+([[:digit:]]))
            get_json "https://www.elektroda.pl/rtvforum/$1.html";;
    esac
    shift
done
