#!/bin/bash
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

shopt -s extglob

declare maxprocs='16'

IFS=$'\n'

ucurl() {
    curl -L -g -s --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' -H 'elektrodaLang=pl' --compressed "$@"
}

declare -r arg0="$(basename "$0")"

usage() {
    printf '%s [dir]\nAdd pages to dir\n' "$arg0"
}

usage() {
    printf '%s [OPTION]... [DIR] [URL]...\n' "${0##*/}"
    printf 'Download, convert to json and save pages from URL in DIR.\n\n'
    printf 'Options:\n  -p,\t--max-procs NUM\tset number of processes to run at a time, by default set to 16\n'
    printf '  -h,\t--help\t\tshow this message\n\n'
    printf 'Note that options ought to be specified before the directory.\n'
}

get_json() {
    local -r rh="${1%.html}"
    local -r name="${rh#https://*/rtvforum/topic}"
    [ -e "$name" ] && return
    echo "$1" >&2
    ucurl "$1" | reliq '
        .locked.b a .reply-bttn | "%i" / sed "s/.*Zamkni.*/t/p" "n",
        .title h1 class=a>topic-title-editor | "%i\n" / sed "/^$/d",
        .path.a ul .breadcrumbs [0]; [2:] span itemprop=name | "%i\n",
        .time span .time | "%i" / sed "s/^.*> //; s/ *$//",
        .views span .views | "%i" / sed "s/^.*> //; s/ //g",
        .replies span .replies | "%i" / sed "s/^.*> //; s/ //g",
        .posts div .topic-lists-wrap; li; {
            .id.u li l@[0] id | "%(id)v",
            .author span .hidden-xs | "%i",
            .level div .level; * c@[0] | "%i" / sed "s/ &emsp;//",
            .time time datetime [0] | "%(datetime)v",
            .text div .text-wrap | "%i"
        } |
    ' | recode ISO-8859-2..UTF8 | jq -srcM --arg 'link' "$1" '{"link":$link}+.[0]' > "$name"
}

get_sitemap() {
    for j in $(ucurl "$1" | reliq 'loc i@B>"^https://www.elektroda.pl/rtvforum/topic[0-9]*" | "%i\n"')
    do
       [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
        get_json "$j" &
    done
    wait
}

get_sitemaps() {
	for i in $(ucurl 'https://www.elektroda.pl/sitemap.xml' | reliq 'loc i@B>"^https://www.elektroda.pl/forum-gf[0-9]*" | "%i\n"')
	do
        echo "$i" >&2
        get_sitemap "$i"
	done
    wait
}

get_page() {
    for j in $(ucurl "$1" | reliq 'tr; h2; a | "https://www.elektroda.pl%(href)v\n"')
    do
       [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
       get_json "$j" &
    done
    wait
}

get_forum() {
    next="$1"
    while :
    do
        echo "$next" >&2
        t1="$(ucurl "$next")"
        next="$(reliq 'a .next | "https://www.elektroda.pl%(href)v\n"' <<< "$t1" | head -n1)"
        for j in $(reliq 'tr; h2; a | "https://www.elektroda.pl%(href)v\n"' <<< "$t1")
        do
            [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
            get_json "$j" &
        done
        wait
        [ -z "$next" ] && break
    done
}

get_forums() {
    for i in $(ucurl 'https://www.elektroda.pl/rtvforum/forums.html' | reliq 'div #B>category-[0-9]*; a href=B>"/rtvforum/forum[0-9]*\.html" | "https://www.elektroda.pl%(href)v\n"')
	do
        get_forum "$i"
	done
}

while [ "$#" -gt 0 ]
do
    case "$1" in
        -p|--max-procs) maxprocs="$2"; shift;;
        -h|--help) usage >&2; exit;;
        -*) usage >&2; exit 1;;
        *) break;;
    esac
    shift
done

if [ "$#" -lt '1' ]
then
    usage >&2
    exit 1
fi

cd "$1" || exit 1

while [ "$#" -gt 0 ]
do
    case "$1" in
        https://www.elektroda.pl?([/])|elektroda|https://www.elektroda.pl/sitemap.xml|sitemap)
            get_sitemaps;;

        https://www.elektroda.pl/forum-gf+([[:digit:]])-+([[:digit:]]).xml|https://www.elektroda.pl/forum-gf+([[:digit:]]).xml)
            get_sitemap "$1";;
        forum-gf+([[:digit:]])-+([[:digit:]]).xml|forum-gf+([[:digit:]]).xml)
            get_sitemap "https://www.elektroda.pl/$1";;
        forum-gf+([[:digit:]])|forum-gf+([[:digit:]])-+([[:digit:]]))
            get_sitemap "https://www.elektroda.pl/$1.xml";;

        forums)
            get_forums;;
        https://www.elektroda.pl/rtvforum/forum+([[:digit:]]).html)
            get_forum "$1";;
        forum+([[:digit:]]).html)
            get_forum "https://www.elektroda.pl/rtvforum/$1";;
        forum+([[:digit:]]))
            get_forum "https://www.elektroda.pl/rtvforum/$1.html";;

        https://www.elektroda.pl/rtvforum/forum+([[:digit:]])-+([[:digit:]]).html)
            get_page "$1";;
        forum+([[:digit:]])-+([[:digit:]]).html)
            get_page "https://www.elektroda.pl/rtvforum/$1";;
        forum+([[:digit:]])-+([[:digit:]]))
            get_page "https://www.elektroda.pl/rtvforum/$1.html";;

        https://www.elektroda.pl/rtvforum/topic+([[:digit:]]).html)
            get_json "$1";;
        +([[:digit:]]).html)
            get_json "https://www.elektroda.pl/rtvforum/topic$1";;
        +([[:digit:]]))
            get_json "https://www.elektroda.pl/rtvforum/topic$1.html";;
        topic+([[:digit:]]).html)
            get_json "https://www.elektroda.pl/rtvforum/$1";;
        topic+([[:digit:]]))
            get_json "https://www.elektroda.pl/rtvforum/$1.html";;
    esac
    shift
done
